export { products }
let products = [
    {
        "name": "iPhone 14 Pro Max",
        "description": "The new iPhone 14 Pro Max is Apple's most powerful and advanced phone. With its new A16 Bionic chip, revolutionary camera, and sleek design, it's the perfect phone for anyone who wants the best.",
        "brand": "Apple",
        "imageUrl": "https://m.media-amazon.com/images/I/610pghkO81L._AC_SX679_.jpg",
        "price": 1199.00,
    },
    {
        "name": "Samsung Galaxy S23 Ultra",
        "description": "The new Samsung Galaxy S23 Ultra is the most powerful and advanced Android phone on the market. With its new Snapdragon 8 Gen 2 processor, 200-megapixel camera, and 6.8-inch QHD+ display, it's the perfect phone for anyone who wants the best.",
        "brand": "Samsung",
        "imageUrl": "https://m.media-amazon.com/images/I/71KzRpQo3CL.__AC_SX300_SY300_QL70_ML2_.jpg",
        "price": 1299.00,
    },
    {
        "name": "MacBook Pro M2 Pro",
        "description": "The new MacBook Pro M2 Pro is Apple's most powerful and advanced laptop. With its new M2 Pro chip, Liquid Retina XDR display, and up to 21 hours of battery life, it's the perfect laptop for anyone who wants the best.",
        "brand": "Apple",
        "imageUrl": "https://m.media-amazon.com/images/I/61NRYreJ2cL._AC_SL1500_.jpg",
        "price": 2999.00,
    },
    {
        "name": "Dell XPS 15 9530 Laptop",
        "description": "The new Dell XPS 15 9530 is Dell's thinnest and lightest laptop. With its new Intel Core i7-13700H processor, 15.6-inch OLED display, and up to 12 hours of battery life, it's the perfect laptop for anyone who wants a powerful and portable device.",
        "brand": "Dell",
        "imageUrl": "https://m.media-amazon.com/images/I/51WHKlaWhGL._AC_SX450_.jpg",
        "price": 2649.00,
    },
    {
        "name": "Asus ROG Zephyrus G14",
        "description": "The Asus ROG Zephyrus G14 is the thinnest and lightest gaming laptop on the market. With its new AMD Ryzen 9 7900HS processor, NVIDIA GeForce RTX 3070 Ti graphics card, and 14-inch IPS display with 120 Hz refresh rate, it's the perfect laptop for anyone who wants to game at the highest level.",
        "brand": "Asus",
        "imageUrl": "https://m.media-amazon.com/images/I/711IiPM6gZL._AC_UY218_.jpg",
        "price": 1999.00,
    },
    {
        "name": "Logitech G502 Hero",
        "description": "The Logitech G502 Hero is the most popular gaming mouse in the world. With its Hero 25K sensor, 11 programmable buttons, and adjustable weight, it's the perfect mouse for anyone who wants to win.",
        "brand": "Logitech",
        "imageUrl": "https://m.media-amazon.com/images/I/61mpMH5TzkL._AC_UY218_.jpg",
        "price": 59.99,
    },
    {
        "name": "Sony PlayStation 5",
        "description": "The new PlayStation 5 is the most powerful gaming console on the market. With its new AMD Ryzen Zen 2 processor and AMD RDNA 2 graphics card, it's the perfect console for anyone who wants to play the latest games at the highest level.",
        "brand": "Sony",
        "imageUrl": "https://m.media-amazon.com/images/I/51UjxChW5fL._AC_UY218_.jpg",
        "price": 499.99,
    },
    {
        "name": "Xbox Series X",
        "description": "The new Xbox Series X is the most powerful gaming console from Microsoft. With its new AMD Zen 2 processor and AMD RDNA 2 graphics card, it's the perfect console for anyone who wants to play the latest games at the highest level.",
        "brand": "Microsoft",
        "imageUrl": "https://m.media-amazon.com/images/I/61BVvNo8E-L._AC_UY218_.jpg",
        "price": 499.99,
    },
    {
        "name": "Apple Watch Series 8",
        "description": "The Apple Watch Series 8 is Apple's most advanced smartwatch. With its new ECG sensor, body temperature measurement, and always-on display, it's the perfect smartwatch for anyone who wants to stay fit and connected.",
        "brand": "Apple",
        "imageUrl": "https://m.media-amazon.com/images/I/71D0KrfAFUL._AC_UY218_.jpg",
        "price": 399.00,
    },
    {
        "name": "Samsung Galaxy Watch 5",
        "description": "The Samsung Galaxy Watch 5 is Samsung's most advanced smartwatch. With its new ECG sensor, blood pressure measurement, and AMOLED always-on display, it's the perfect smartwatch for anyone who wants to stay fit and connected.",
        "brand": "Samsung",
        "imageUrl": "https://m.media-amazon.com/images/I/51Gg2lEe8-L._AC_UY218_.jpg",
        "price": 299.99,
    },
    {
        "name": "Nintendo Switch OLED",
        "description": "The new Nintendo Switch OLED is the most advanced portable console from Nintendo. With its new 7-inch OLED display, larger battery, and adjustable stand, it's the perfect console for anyone who wants to play their favorite games anywhere.",
        "brand": "Nintendo",
        "imageUrl": "https://m.media-amazon.com/images/I/71eVf1+jn6L._AC_UY218_.jpg",
        "price": 349.99,
    },
    {
        "name": "AirPods Pro",
        "description": "The AirPods Pro are Apple's most advanced wireless earbuds. With their in-ear design, active noise cancellation, and transparency mode, they're the perfect earbuds for anyone who wants to listen to music, make calls, or simply enjoy their surroundings.",
        "brand": "Apple",
        "imageUrl": "https://m.media-amazon.com/images/I/61CVih3UpdL._AC_UY218_.jpg",
        "price": 279.00,
    },
    {
        "name": "Samsung Galaxy Z Fold 4",
        "description": "The new Samsung Galaxy Z Fold 4 is Samsung's most advanced foldable phone. With its new thinner and lighter design, larger internal display, and more powerful processor, it's the perfect phone for anyone who wants the ultimate productivity and entertainment.",
        "brand": "Samsung",
        "imageUrl": "https://m.media-amazon.com/images/I/61dEmk5lHbL._AC_UY218_.jpg",
        "price": 1899.00,
    },
    {
        "name": "Oculus Quest 2",
        "description": "The Oculus Quest 2 is the most popular virtual reality headset on the market. With its lightweight and comfortable design, high-resolution display, and vast library of games and apps, it's the perfect headset for anyone who wants to immerse themselves in the world of virtual reality.",
        "brand": "Meta",
        "imageUrl": "https://m.media-amazon.com/images/I/61kwRNPtMpL._AC_UY218_.jpg",
        "price": 299.99,
    },
    {
        "name": "Sony WH-1000XM5",
        "description": "The Sony WH-1000XM5 are Sony's most advanced wireless earbuds with active",
        "brand": "Sony",
        "imageUrl": "https://m.media-amazon.com/images/I/61fxPWFu6aL._AC_UY218_.jpg",
        "price": 399.99,
    },
    {
        "name": "Philips Hue White Ambiance E27",
        "description": "Philips Hue White Ambiance E27 smart LED bulbs can be used to create the perfect atmosphere in any room. With their wide range of colors and intensities, they are the perfect bulbs for anyone who wants to personalize their environment.",
        "brand": "Philips",
        "imageUrl": "https://m.media-amazon.com/images/I/615CA341UnL._AC_UL320_.jpg",
        "price": 29.99,
    }
];